"""add user models

Revision ID: 4ae8fb739458
Revises: 
Create Date: 2024-10-06 21:45:49.774931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae8fb739458'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('teachers_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('students_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('groups_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('hashed_password', sa.String(length=65), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
